### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by serialame** [ookiineko/CollectionDowngrader#1]
Found realm file.
Error opening database:

Provided schema version 30 does not equal last set version 26.
It seemed like the specified osu! (lazer) database is in a new format which is not compatible with this version of CollectionDowngrader.

You can go check the project page to see if there's a new release, or file an Issue on GitHub to let me know it needs updating. ^^

**Comment by serialame** [comment]
nvm my lazer was too old

**Comment by ghost** [comment]
> nvm my lazer was too old

if you want to use it with lower lazer version, download the old release builds

**Comment by ghost** [comment]
thanks for pointing out the mistake in the error msg, i will fix it later
